import './globals.css';
import { Arimo } from 'next/font/google';

const arimo = Arimo({ subsets: ['latin'], weight: ["400"], })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arimo.className}>{children}</body>
    </html>
  )
}
